FROM php:7.4-apache

WORKDIR /var/www/html
COPY index.php /var/www/html
COPY conexao.php /var/www/html

RUN apt-get update -y
RUN apt-get install -y libfreetype6-dev
RUN apt-get install -y  libjpeg62-turbo-dev
RUN apt-get install -y libpng-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg 
RUN docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli


EXPOSE 80